WIP: add new function like the github one
also manage CACHE for gitlab style
and add gitlab source to pretty list and docs

diff --git a/deb-get b/deb-get
--- a/deb-get
+++ b/deb-get
@@ -172,6 +172,28 @@ function get_github_releases() {
     fi
 }
 
+function get_gitlab_releases() {
+    METHOD="gitlab"
+    CACHE_FILE="${CACHE_DIR}/${APP}.json"
+    # Cache gitlab releases json for 1 hour to try and prevent API rate limits
+    # 
+    # Do not process gitlab releases while generating a pretty list or upgrading
+    if [[ ' install update fix-installed ' =~ " ${ACTION} " ]]; then
+        if [ ! -e "${CACHE_FILE}" ] || [ -n "$(find "${CACHE_FILE}" -mmin +"${DEBGET_CACHE_RTN:-60}")" ]; then
+            fancy_message info "Updating ${CACHE_FILE}"
+
+            local URL="https://gitlab.com/api/v4/projects/${1}/releases/" #${2:+/$2}"
+            # wgetcmdarray=(wget  "${HEADERPARAM}" "${HEADERAUTH}" -q --no-use-server-timestamps "${URL}" -O "${CACHE_FILE}")
+            wgetcmdarray=(wget -q --no-use-server-timestamps "${URL}" -O "${CACHE_FILE}")
+            
+            ${ELEVATE} "${wgetcmdarray[@]}" || ( fancy_message warn "Updating ${CACHE_FILE} failed." )
+            # if [ -f "${CACHE_FILE}" ] && grep "API rate limit exceeded" "${CACHE_FILE}"; then
+            #     fancy_message warn "Updating ${CACHE_FILE} exceeded GitHub API limits. Deleting it."
+            #     ${ELEVATE} rm "${CACHE_FILE}" 2>/dev/null
+            # fi
+        fi
+    fi
+}
 function get_website() {
     METHOD="website"
     CACHE_FILE="${CACHE_DIR}/${APP}.html"
