force all app testing
filter ppas from debians

diff --git a/.github/workflows/tests-01-main.yml b/.github/workflows/tests-01-main.yml
--- a/.github/workflows/tests-01-main.yml
+++ b/.github/workflows/tests-01-main.yml
@@ -45,7 +45,7 @@ jobs:
 
       - name: Initialize /etc/deb-get
         run: |
-          sudo mkdir /etc/deb-get
+          sudo mkdir /etc/deb-get 2>/dev/null || true
           echo "deb-get 1 github" | sudo tee /etc/deb-get/installed > /dev/null
           sudo cp ./01-main/manifest /etc/deb-get/01-main.repo
           sudo cp -r ./01-main/packages /etc/deb-get/01-main.d
@@ -68,3 +68,26 @@ jobs:
               fi
             fi
           done
+
+      - name: Debian testing
+        run: |
+          export DEBIAN_FRONTEND=noninteractive
+          set -x
+          . /etc/os-release
+          if [ $ID == debian ] ; then
+            APPS="$(./deb-get csv |grep -v -e ppa -e virtualbox|cut -d\" -f2 )"
+          else
+            APPS="$(./deb-get csv |grep -v -e virtualbox|cut -d\" -f2 )"
+          fi
+          for APP in ${APPS}; do
+            if grep -q -m 1 "^${APP}$" ./01-main/manifest; then
+              ./deb-get install "${APP}"
+              if ./deb-get show "${APP}" | grep -q "Installed:	No"; then
+                echo "Failed to detect ${APP} as installed" >&2
+                exit 1
+              else
+                ./deb-get purge "${APP}"
+              fi
+            fi
+            done
+
